### PR TITLE
Accept GitHub auth token for releases in private repos

### PR DESCRIPTION
**Pull request by dmcgillen**

### CODE REVIEW

**Comment by dmcgillen** [comment]
As the title says, this allows an auth token to be provided when calling doing an update so that this library can be used for private repos.

To support this, I've also changed the download call to use the GitHub api to download the asset rather than the browser url so that the Authorization header can be provided.

I've had to add headers as a parameter to Download to support this too.

I've only been doing Rust for a couple of weeks so I hope this is ok!

**Comment by jaemk** [comment]
Are you able to scope GitHub auth tokens to only allow downloading releases artifacts?

**Comment by dmcgillen** [comment]
I think they require the top level repo scope (full control of private repositories).

**Comment by dmcgillen** [comment]
Hi there, any joy with this? Let me know if there's anything you want me to help with or change. Thanks!

**Comment by jaemk** [comment]
I'm worried about security issues of distributing a personal access token in applications. Can you test what the minimum access token permissions are for downloading private releases? Restricting the token to read-only may be sufficient. Can we also add some warnings in the documentation to remind users that they should be careful when adding access tokens?
If there's no way to limit the scope of tokens to releases or being read-only, I'd prefer if we didn't add the  `auth_token` builder method, and instead require manually setting the it through a `header` or `headers` builder method.

**Comment by dmcgillen** [comment]
Sorry but I don't quite understand. Users don't need to distribute tokens in applications. In the CLI tool I use this in for example, I check an environment variable for the GitHub token and read it from there. I could have also asked the user of the tool to input it, just like many command line programs would ask for a password. It's like anything really, if I use an AWS SDK I need credentials, but I don't store them in my app, or database passwords etc. Am I missing something? Happy to make changes of course (and to be more explicit in the readme) just not entirely sure there's a problem.

**Comment by jaemk** [comment]
Got it -- that makes more sense. Sorry, the examples made it seem like you wanted to embed the tokens (`.auth_token("0123456789abcdef0123456789abcdef01234567")`).

Would you mind changing the examples to read the token from an env var
```
//.auth_token(env!("ACCESS_TOKEN"))
```
And updating the documentation to mention that the token should come from the env or user input and not a static str.

Might be cool, but not necessary, to add support for automatically reading from an env or prompting the user
```
.auth_token_from_env(...)
.auth_token_prompt("Enter download token >>")
```

**Comment by dmcgillen** [comment]
Sorry, I realise now that it's not that clear in my example. Your suggestions sound like a good idea, I'll get those in and update the PR. Many thanks!

**Comment by dmcgillen** [comment]
I've made the doc changes as requested. Hope they're ok, let me know.

Would you like me to add the other methods or is this PR ok to go without them? I attempted to do it this evening but my Rust ability is still quite low so it's taking longer than I'd hoped!

**Comment by jaemk** [comment]
thanks!

**Pull request merged**
