### PR TITLE
Add FreeBSD support

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by jaemk** [comment]
Can you also uncommented the two freebsds in the [.travis.yml](https://github.com/jaemk/self_update/blob/master/.travis.yml) build matrix?

**Comment by r-darwish** [comment]
Done

**Comment by r-darwish** [comment]
`DISABLE_TESTS` is [commented out](https://github.com/jaemk/self_update/blob/master/ci/script.sh#L10). Running tests isn't possible when cross compiling.

**Comment by jaemk** [comment]
ah, thanks

**Pull request merged**
