### PR TITLE
Gitlab support

### PR DESCRIPTION
**Pull request by Silver-Golden**
Using the GitHub backend as a base I added Gitlab support.

Followed CONTRIBUTING.md.  
Would have liked to have added ``cargo run --example gitlab`` to the testing but I havent set up a repo there for the purporse of testing, it does work for my own project which I plan to use it in.

This should tackle #31

### CODE REVIEW

**Comment by jaemk** [comment]
Nice, thanks! Looks good to me. I'm going to setup a gitlab repo that we can run an example against before I merge

**Comment by Silver-Golden** [comment]
Did you get round to setting up a gitlab repo for it?

If you need to you can probally use the url from the releases on this (github) repo in the gitlab one, they dont actually lock you in to using gitlab links only.

As for creating an account you can sign into gitlab with  github oauth.

**Comment by jaemk** [comment]
Woops, my bad - I'll definitely get to it this weekend

**Comment by jaemk** [comment]
thanks again!

**Comment by jaemk** [comment]
released in 0.17.0

**Comment by Silver-Golden** [comment]
Woot!

I'll update my own project to use the main repo now.

And thank you to be willing to add it.

**Comment by Silver-Golden** [comment]
oh and #31 can probally be closed out as that was specifically anout gitlab support.

**Pull request merged**
